qlsvHoang/Controllers/AuthenController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using qlsvHoang.Data;
using qlsvHoang.Models;
using qlsvHoang.Service.FacadePattern;
using qlsvHoang.Service.IService;
using qlsvHoang.ViewModel;
using System.Security.Claims;

namespace qlsvHoang.Controllers
{
    public class AuthenController : Controller
    {
        private readonly ITeacherService teacherService;
        private readonly IAdminService adminService;
        private readonly StudentFacade facade;
        private readonly qlsvHoangContext _context;

        public AuthenController(ITeacherService teacherService, IAdminService adminService, qlsvHoangContext context)
        {
            this.teacherService = teacherService;
            this.adminService = adminService;
            _context = context;
            facade = new StudentFacade(context);
        }
        [HttpGet]
        public IActionResult LoginAdmin()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> LoginAdmin(AdminLoginVM adminLogin)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    var res = await adminService.LoginAdmin(adminLogin);
                    if (res != null)
                    {
                        var role = await _context.Roles.FirstOrDefaultAsync(r => r.RoleId == res.RoleId);
                        var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.NameIdentifier, res.AdminId.ToString()),
                        new Claim(ClaimTypes.Role, "Admin"),
                        new Claim(ClaimTypes.Name,res.Name),
                    };
                        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                        var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

                        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal);

                        TempData["ok"] = "Login Successful !";
                        return RedirectToAction("DashBoard", "Admins");
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Invalid username or password.";
                        TempData["no"] = "Login Failed !";
                        return View();
                    }
                }
                return View();

            }
            catch (Exception ex)
            {
                throw ex;
            }

        }

        [HttpGet]
        public IActionResult LoginStudent()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> LoginStudent(LoginStudentVM loginStudentVM)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    var login = await facade.loginStudent(loginStudentVM);
                    if (login != null)
                    {
                        var role = await _context.Roles.FirstOrDefaultAsync(r => r.RoleId == login.RoleId);
                        var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.NameIdentifier, login.StudentId.ToString()),
                        new Claim(ClaimTypes.Role, "Student"),
                        new Claim(ClaimTypes.Name,login.Name),
                    };
                        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                        var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

                        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal);

                        TempData["ok"] = "Login Successful !";
                        return RedirectToAction("DashBoard", "Students");
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Invalid username or password.";
                        TempData["no"] = "Login Failed !";
                        return View();
                    }
                }
                return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }




        [HttpGet]
        public IActionResult LoginTeacher()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> LoginTeacher(LoginTeacherVM loginTeacherVM)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    var login = await teacherService.loginTeacher(loginTeacherVM);
                    if (login != null)
                    {
                        var role = await _context.Roles.FirstOrDefaultAsync(r => r.RoleId == login.RoleId);
                        var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.NameIdentifier, login.TeacherId.ToString()),
                        new Claim(ClaimTypes.Role, "Teacher"),
                        new Claim(ClaimTypes.Name,login.Name),
                    };
                        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                        var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

                        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal);

                        TempData["ok"] = "Login Successful !";
                        return RedirectToAction("DashBoard", "Teachers");
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Invalid username or password.";
                        TempData["no"] = "Login Failed !";
                        return View();
                    }
                }
                return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }



        public async Task<IActionResult> Logout()

        {
            await HttpContext.SignOutAsync();
            TempData["ok"] = "See you again!";
            return Redirect("/");
        }


        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

qlsvHoang/Views/Authen/AccessDenied.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - 404</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    <style>
    

*{
  margin:0;
  padding:0;
  box-sizing:border-box;
}

body{
  overflow:hidden;
  background-color: #f4f6ff;
}

.container{
  width:100vw;
  height:100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  font-family: "Poppins", sans-serif;
  position: relative;
  left:6vmin;
  text-align: center;
}

.cog-wheel1, .cog-wheel2{
  transform:scale(0.7);
}

.cog1, .cog2{
  width:40vmin;
  height:40vmin;
  border-radius:50%;
  border:6vmin solid #f3c623;
  position: relative;
}


.cog2{
  border:6vmin solid #4f8a8b;
}

.top, .down, .left, .right, .left-top, .left-down, .right-top, .right-down{
  width:10vmin;
  height:10vmin;
  background-color: #f3c623;
  position: absolute;
}

.cog2 .top,.cog2  .down,.cog2  .left,.cog2  .right,.cog2  .left-top,.cog2  .left-down,.cog2  .right-top,.cog2  .right-down{
  background-color: #4f8a8b;
}

.top{
  top:-14vmin;
  left:9vmin;
}

.down{
  bottom:-14vmin;
  left:9vmin;
}

.left{
  left:-14vmin;
  top:9vmin;
}

.right{
  right:-14vmin;
  top:9vmin;
}

.left-top{
  transform:rotateZ(-45deg);
  left:-8vmin;
  top:-8vmin;
}

.left-down{
  transform:rotateZ(45deg);
  left:-8vmin;
  top:25vmin;
}

.right-top{
  transform:rotateZ(45deg);
  right:-8vmin;
  top:-8vmin;
}

.right-down{
  transform:rotateZ(-45deg);
  right:-8vmin;
  top:25vmin;
}

.cog2{
  position: relative;
  left:-10.2vmin;
  bottom:10vmin;
}

h1{
  color:#142833;
}

.first-four{
  position: relative;
  left:6vmin;
  font-size:40vmin;
}

.second-four{
  position: relative;
  right:18vmin;
  z-index: -1;
  font-size:40vmin;
}

.wrong-para{
  font-family: "Montserrat", sans-serif;
  position: absolute;
  bottom:15vmin;
  padding:3vmin 12vmin 3vmin 3vmin;
  font-weight:600;
  color:#092532;
}
    </style>
</head>

<body >

    <div class="container">
        <h1 class="first-four">4</h1>
        <div class="cog-wheel1">
            <div class="cog1">
                <div class="top"></div>
                <div class="down"></div>
                <div class="left-top"></div>
                <div class="left-down"></div>
                <div class="right-top"></div>
                <div class="right-down"></div>
                <div class="left"></div>
                <div class="right"></div>
            </div>
        </div>

        <div class="cog-wheel2">
            <div class="cog2">
                <div class="top"></div>
                <div class="down"></div>
                <div class="left-top"></div>
                <div class="left-down"></div>
                <div class="right-top"></div>
                <div class="right-down"></div>
                <div class="left"></div>
                <div class="right"></div>
            </div>
        </div>
        <h1 class="second-four">4</h1>
        <p class="wrong-para">Uh Oh! AccessDenied !</p>
    </div>
    <script>
        let t1 = gsap.timeline();
let t2 = gsap.timeline();
let t3 = gsap.timeline();

t1.to(".cog1",
{
  transformOrigin:"50% 50%",
  rotation:"+=360",
  repeat:-1,
  ease:Linear.easeNone,
  duration:8
});

t2.to(".cog2",
{
  transformOrigin:"50% 50%",
  rotation:"-=360",
  repeat:-1,
  ease:Linear.easeNone,
  duration:8
});

t3.fromTo(".wrong-para",
{
  opacity:0
},
{
  opacity:1,
  duration:1,
  stagger:{
    repeat:-1,
    yoyo:true
  }
});
    </script>

</body>

</html>

qlsvHoang/Views/Authen/LoginAdmin.cshtml
@model qlsvHoang.Models.Admin

@{
    ViewData["Title"] = "Login Admin";
    Layout = null;
}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.css" />
    <title>Login Admin</title>
</head>

<body>
    <div class="d-lg-flex half">
        <div class="bg order-1" style="background-image: url('/assets/images/test.jpg');"></div>
        <div class="contents order-2 order-md-1">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-md-7">
                        <h3>Login to <strong>Management Student </strong></h3>
                        <p class="mb-4">Welcome back! Select login method:</p>
                        <div class="social d-flex text-center">
                            <a asp-controller="Authen" asp-action="LoginStudent" class="abc" style="color: black; background-color: white">Student</a>
                            <a asp-controller="Authen" asp-action="LoginTeacher" class="xyz" style="color: black; background-color: white">Teacher</a>
                            <a asp-controller="Authen" asp-action="LoginAdmin" class="abc">Admin</a>
                        </div>

                        <form asp-action="LoginAdmin" asp-route-returnurl="@ViewBag.ReturnUrl">
                            <div class="form-group first">
                                <label asp-for="@Model.Username" class="form-label my-3"></label>
                                <sup>*</sup>
                                <input asp-for="@Model.Username" class="form-control" placeholder="Enter username" required>
                                <span asp-validation-for="@Model.Username" class="text-danger"></span>
                            </div>
                            <div class="form-group last mb-3">
                                <label asp-for="@Model.Password" class="form-label my-3"></label>
                                <sup>*</sup>
                                <input asp-for="@Model.Password" class="form-control" placeholder="Enter password" type="password" required>
                                <span asp-validation-for="@Model.Password" class="text-danger"></span>
                            </div>
                            <div class="d-flex mb-3 align-items-center">
                                <span class="text-danger">@ViewBag.ErrorMessage</span>
                            </div>
                            <button type="submit" class="btn btn-block btn-primary"> Log In </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.js"></script>

    @if (TempData["ok"] != null)
    {
        <script>
            $(document).ready(function () {
                $.toast({
                    heading: 'Notification',
                    text: "@TempData["ok"]",
                    showHideTransition: 'slide',
                    icon: 'success',
                    position: 'top-center',
                    hideAfter: 3000
                });
            });
        </script>
    }
    else if (TempData["no"] != null)
    {
        <script>
            $(document).ready(function () {
                $.toast({
                    heading: 'Notification',
                    text: "@TempData["no"]",
                    showHideTransition: 'slide',
                    icon: 'error',
                    position: 'top-center',
                    hideAfter: 10000
                });
            });
        </script>
    }
</body>
</html>

qlsvHoang/Views/Authen/LoginStudent.cshtml
@model qlsvHoang.Models.Student

@{
    ViewData["Title"] = "Login Student";
    Layout = null;
}



<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.css" />
    <title>Login Admin</title>
</head>

<body>
    <div class="d-lg-flex half">
        <div class="bg order-1" style="background-image: url('/assets/images/test.jpg');"></div>
        <div class="contents order-2 order-md-1">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-md-7">
                        <h3>Login to <strong>Management Student </strong></h3>
                        <p class="mb-4">Welcome back! Select login method:</p>
                        <div class="social d-flex text-center">
                            <a asp-controller="Authen" asp-action="LoginStudent" class="abc">Student</a>
                            <a asp-controller="Authen" asp-action="LoginTeacher" class="xyz" style="color: black; background-color: white">Teacher</a>
                            <a asp-controller="Authen" asp-action="LoginAdmin" class="abc" style="color: black; background-color: white">Admin</a>
                        </div>

                        <form asp-action="LoginStudent" asp-route-returnurl="@ViewBag.ReturnUrl">
                            <div class="form-group first">
                                <label asp-for="@Model.Username" class="form-label my-3"></label>
                                <sup>*</sup>
                                <input asp-for="@Model.Username" class="form-control" placeholder="Enter username" required>
                                <span asp-validation-for="@Model.Username" class="text-danger"></span>
                            </div>
                            <div class="form-group last mb-3">
                                <label asp-for="@Model.Password" class="form-label my-3"></label>
                                <sup>*</sup>
                                <input asp-for="@Model.Password" class="form-control" placeholder="Enter password" type="password" required>
                                <span asp-validation-for="@Model.Password" class="text-danger"></span>
                            </div>
                            <div class="d-flex mb-3 align-items-center">
                                <span class="text-danger">@ViewBag.ErrorMessage</span>
                            </div>
                            <div class="col-md-12">
                                <div class="row d-flex justify-content-between">
                                    <button type="submit" class="col-md-5 btn btn-block btn-primary mr-1  "> Log In </button>

                                    <div class="col-md-5"> <a class="w-100 btn btn-block btn-primary mt-0 text-decoration-none pt-3 text-white" asp-controller="Students" asp-action="CreateStudent">   Resgiter</a></div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.js"></script>

    @if (TempData["ok"] != null)
    {
        <script>
            $(document).ready(function () {
                $.toast({
                    heading: 'Notification',
                    text: "@TempData["ok"]",
                    showHideTransition: 'slide',
                    icon: 'success',
                    position: 'top-center',
                    hideAfter: 3000
                });
            });
        </script>
    }
    else if (TempData["no"] != null)
    {
        <script>
            $(document).ready(function () {
                $.toast({
                    heading: 'Notification',
                    text: "@TempData["no"]",
                    showHideTransition: 'slide',
                    icon: 'error',
                    position: 'top-center',
                    hideAfter: 10000
                });
            });
        </script>
    }
</body>
</html>

qlsvHoang/Views/Authen/LoginTeacher.cshtml
@model qlsvHoang.Models.Teacher

@{
    ViewData["Title"] = "Login Admin";
    Layout = null;
}



<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.css" />
    <title>Login Admin</title>
</head>

<body>
    <div class="d-lg-flex half">
        <div class="bg order-1" style="background-image: url('/assets/images/test.jpg');"></div>
        <div class="contents order-2 order-md-1">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-md-7">
                        <h3>Login to <strong>Management Student </strong></h3>
                        <p class="mb-4">Welcome back! Select login method:</p>
                        <div class="social d-flex text-center">
                            <a asp-controller="Authen" asp-action="LoginStudent" class="abc" style="color: black; background-color: white">Student</a>
                            <a asp-controller="Authen" asp-action="LoginTeacher" class="xyz" >Teacher</a>
                            <a asp-controller="Authen" asp-action="LoginAdmin" class="abc" style="color: black; background-color: white">Admin</a>
                        </div>

                        <form asp-action="LoginTeacher" asp-route-returnurl="@ViewBag.ReturnUrl">
                            <div class="form-group first">
                                <label asp-for="@Model.Username" class="form-label my-3"></label>
                                <sup>*</sup>
                                <input asp-for="@Model.Username" class="form-control" placeholder="Enter username" required>
                                <span asp-validation-for="@Model.Username" class="text-danger"></span>
                            </div>
                            <div class="form-group last mb-3">
                                <label asp-for="@Model.Password" class="form-label my-3"></label>
                                <sup>*</sup>
                                <input asp-for="@Model.Password" class="form-control" placeholder="Enter password" type="password" required>
                                <span asp-validation-for="@Model.Password" class="text-danger"></span>
                            </div>
                            <div class="d-flex mb-3 align-items-center">
                                <span class="text-danger">@ViewBag.ErrorMessage</span>
                            </div>
                            <button type="submit" class="btn btn-block btn-primary"> Log In </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.js"></script>

    @if (TempData["ok"] != null)
    {
        <script>
            $(document).ready(function () {
                $.toast({
                    heading: 'Notification',
                    text: "@TempData["ok"]",
                    showHideTransition: 'slide',
                    icon: 'success',
                    position: 'top-center',
                    hideAfter: 3000
                });
            });
        </script>
    }
    else if (TempData["no"] != null)
    {
        <script>
            $(document).ready(function () {
                $.toast({
                    heading: 'Notification',
                    text: "@TempData["no"]",
                    showHideTransition: 'slide',
                    icon: 'error',
                    position: 'top-center',
                    hideAfter: 10000
                });
            });
        </script>
    }
</body>
</html>